services:
  app_3d_blazor:
    image: ${DOCKER_REGISTRY-}app3dblazor
    build:
      context: APP_3D_Blazor
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Port HTTP
      - "5001:5001" # Port HTTPS