services:
  app_3d_blazor:
    image: ${DOCKER_REGISTRY-}app3dblazor
    build:
      context: APP_3D_Blazor
      dockerfile: Dockerfile
    ports:
      - "8080:5000" # Port HTTP
      - "8443:5001" # Port HTTPS
    volumes:
      - ./certificates:/app/certificates