services:
  app_3d_blazor:
    image: ${DOCKER_REGISTRY-}app3dblazor
    build:
      context: APP_3D_Blazor
      dockerfile: Dockerfile
    ports:
      - "80:5000"  
      - "443:5001" 
    volumes:
      - ./certificates:/app/certificates