services:
  app_3d_blazor:
    image: ${DOCKER_REGISTRY-}app3dblazor
    build:
      context: APP_3D_Blazor
      dockerfile: Dockerfile
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./certificates:/app/certificates